# Generated by Django 3.1.2 on 2023-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230407_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Tag'),
        ),
    ]
